
server.port=8003
server.servlet.context-path=/camundaworkflows

#spring.datasource.url=jdbc:postgresql://localhost:5432/test
#spring.datasource.username=postgres
#spring.datasource.password=Rajesh##7
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.config.import=optional:configserver:http://localhost:9999/config
# Tell Swagger the correct path (important when context-path is set)
springdoc.api-docs.path=/v3/api-docs
#springdoc.api-docs.path=/test/v3/api-docs



springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

camunda.client.mode=self-managed
camunda.client.auth.enabled=false
camunda.client.zeebe.grpc-address=http://100.83.141.117:26500
camunda.client.zeebe.rest-address=http://100.83.141.117:8088

# REST timeout must be greater than long-poll duration
camunda.client.zeebe.defaults.request-timeout=20s
camunda.client.zeebe.defaults.job-worker-long-poll-timeout=10s
 Optional: reduce log noise for this specific logger
logging.level.io.camunda.client.job.poller=ERROR
