server.port=8077
server.servlet.context-path=/pathologyservices

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pathologyservices
spring.datasource.username=postgres
spring.datasource.password=Rajesh##7

# JPA / Hibernate — this creates the tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Springdoc / Swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
